### ISSUE TITLE
Module org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT not found in any repositories

### ISSUE THREAD

**Issue by pinyin** [pac4j/vertx-pac4j-demo#8]
Hi, 

Are the dependencies of the demo outdated?

```
pinyin@notebook:~/Downloads/vertx-pac4j-demo$ mvn vertx:runMod
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building Project - vertx-pac4j-demo 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- vertx-maven-plugin:2.0.11-final:runMod (default-cli) @ vertx-pac4j-demo ---
log4j:WARN No appenders could be found for logger (io.netty.util.internal.logging.InternalLoggerFactory).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] CTRL-C to stop server
Jul 29, 2015 8:22:00 AM org.vertx.java.platform.impl.resolver.HttpResolution
INFO: Downloading com.campudus~session-manager~2.0.1-final. Please wait...
Jul 29, 2015 8:22:00 AM org.vertx.java.platform.impl.DefaultPlatformManager
INFO: Module com.campudus~session-manager~2.0.1-final successfully installed
Jul 29, 2015 8:22:06 AM org.pac4j~vertx-pac4j-demo~1.0.0-SNAPSHOT-org.pac4j.vertx.Pac4jDemo-2040642511
SEVERE: Exception in Java verticle
org.vertx.java.platform.PlatformManagerException: Module org.pac4j~vertx-pac4j-module~1.1.0-SNAPSHOT not found in any repositories
	at org.vertx.java.platform.impl.DefaultPlatformManager.getModule(DefaultPlatformManager.java:1449)
	at org.vertx.java.platform.impl.DefaultPlatformManager.doInstallMod(DefaultPlatformManager.java:1438)
	at org.vertx.java.platform.impl.DefaultPlatformManager.deployModuleFromFileSystem(DefaultPlatformManager.java:1268)
	at org.vertx.java.platform.impl.DefaultPlatformManager.access$1300(DefaultPlatformManager.java:57)
	at org.vertx.java.platform.impl.DefaultPlatformManager$12.run(DefaultPlatformManager.java:462)
	at org.vertx.java.platform.impl.DefaultPlatformManager$14.run(DefaultPlatformManager.java:487)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by leleuj** [comment]
The library has been released, so you should use the version 1.1.0 (the new snapshot is 1.1.1-SNAPSHOT). Normally, the demo is up-to-date, I just ran it successfully.
